create array


In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([-0.38440079,  0.31717698, -0.74276004,  0.19719422,  0.06707341,
       -0.54838135, -2.23688776, -0.98677052, -1.03050785,  0.45134717])

In [3]:
np.random.randint(10)

5

In [5]:
np.random.randint(10,size=(2,3))

array([[2, 4, 2],
       [9, 9, 6]])

In [12]:
np.random.randint(10,size=20).reshape(4,5)

array([[7, 3, 3, 9, 2],
       [4, 0, 5, 1, 8],
       [4, 7, 9, 4, 9],
       [7, 7, 6, 4, 6]])

In [13]:
a=np.random.randint(10,size=20).reshape(4,5)
b=np.random.randint(10,size=20).reshape(4,5)

In [15]:
a+b

array([[15, 10,  8, 12, 14],
       [16, 16, 12, 14, 16],
       [ 8, 10,  8,  7, 11],
       [10,  9,  6, 10,  9]])

In [16]:
a*b  #数组对应元素相乘，不是矩阵乘法

array([[56, 21,  7, 36, 45],
       [64, 63, 27, 45, 63],
       [ 0, 24, 16,  0, 30],
       [25, 14,  0, 24,  0]])

In [24]:
q=np.mat([[1,2,3],[4,5,6]])
p=np.mat([[1,2],[3,4],[5,6]])

In [27]:
np.mat(a)#矩阵与数组互换

matrix([[7, 3, 7, 6, 9],
        [8, 7, 9, 5, 9],
        [8, 6, 4, 7, 6],
        [5, 7, 0, 4, 0]])

In [28]:
a

array([[7, 3, 7, 6, 9],
       [8, 7, 9, 5, 9],
       [8, 6, 4, 7, 6],
       [5, 7, 0, 4, 0]])

In [26]:
q*p#矩阵乘法符合规则

matrix([[22, 28],
        [49, 64]])

Array function lib

In [29]:
a=np.random.randint(10,size=20).reshape(4,5)

In [30]:
a

array([[1, 4, 1, 8, 8],
       [2, 1, 2, 0, 2],
       [4, 9, 2, 7, 9],
       [0, 3, 6, 0, 4]])

In [31]:
sum(a)#列相加

array([ 7, 17, 11, 15, 23])

In [32]:
sum(a[0])#行相加

22

In [70]:
a[:,0:2]

array([[1, 4],
       [2, 1],
       [4, 9],
       [0, 3]])

In [71]:
sum(a[:,0:2])

array([ 7, 17])

In [74]:
a[:,0:1]#列返回

array([[1],
       [2],
       [4],
       [0]])

In [73]:
a[:,0]#以单数组返回

array([1, 2, 4, 0])

In [72]:
sum(a[:,0])

7

In [ ]:
# arrayN维数组：
# list_2=[5,6,7,8]
# array_2=np.array([list_1,list_2])
# array_2.shape  （2，4）
# array_2.size
# array_2.dtype
# np.zeros(5) #全零
# np.eye(5) #单位矩阵
# a=np.arange(1,10)#创建一维数组用arange
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
# Input:
#  c[0:1,1:2]	# 第一个为行、二为列，记住从零开始、最后一个都不要，故相当于[0:0,1:1],0行的第一列
# Out[27]:
#          array([[2]])

# 正态分布随机数组：
# np.random.randn(10)
# np.random.randint(10,size=(2,3))
# np.random.randint(10,size=20).reshape(4,5)  #取10以内20个数，搞成45的数组


# 数组的函数：


# a[:,0:4]  #表示所有行，0到3列的元素

# a[:,0]  	#表示所有行，且是第一列，以数组返回
# array([1, 2, 4, 0])
# a[:,0:1]	#表示所有行，且是第一列，以列返回
# array([[1],
#        [2],
#        [4],
#        [0]])



# 创建矩阵：
# q=np.mat([[1,2,3],[4,5,6]])

# p=np.mat([[1,2],[3,4],[5,6]])
# np.mat(a)#矩阵与数组互换
