使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x=np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f=open('x.pkl','wb')#pickle only use in binary

In [5]:
pickle.dump(x,f)

In [7]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 9495-EDD8

 Directory of C:\Users\ZHAOFENG SHANG\Desktop\NoteBook\OnlineCourse_chinese

01/15/2018  07:26 PM    <DIR>          .
01/15/2018  07:26 PM    <DIR>          ..
01/15/2018  07:26 PM    <DIR>          .ipynb_checkpoints
01/13/2018  09:44 PM            22,338 Aggregation.ipynb
01/13/2018  11:01 PM            40,420 Apply.ipynb
01/12/2018  10:29 AM             7,841 Array.ipynb
01/12/2018  02:55 PM             5,349 Array?input?output.ipynb
01/14/2018  10:27 AM            58,241 Basic Plot.ipynb
01/14/2018  08:48 AM            36,698 Clean Duplicated Data.ipynb
01/13/2018  09:30 AM    <DIR>          course_document
01/13/2018  04:10 PM            13,151 DataFrame Binning.ipynb
01/12/2018  10:44 PM            23,263 DataFrame IO.ipynb
01/15/2018  11:12 AM           172,038 DataFrame Plot.ipynb
01/13/2018  10:59 AM            45,327 DataFrame.ipynb
01/12/2018  10:26 PM               867 df_io.csv
01/12/2018  10:42 PM          

In [8]:
#要重新打开文件

In [9]:
f=open('x.pkl','rb')

In [10]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.save('one_array',x)#numpy 自带方法 save,只能存一个

In [12]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [13]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y=np.arange(20)

In [15]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.savez('two_array.npz',a=x,b=y) #numpy 自带方法 savez,可以多存  savezip

In [17]:
c=np.load('two_array.npz')

In [18]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
# 使用pickle序列化numpy array
# 方法1：

# import pickle
# import numpy as np
# x=np.arange(10)
# f=open('x.pkl','wb')#pickle only use in binary
# pickle.dump(x,f)
# f=open('x.pkl','rb')
# pickle.load(f)
# 方法2：
# numpy自带
# 只能对于存一个：
# np.save('one_array',x)
# np.load('one_array.npy')
# 对于存多个：
# np.savez('two_array.npz',a=x,b=y）
# c=np.load('two_array.npz')
# c['a']
# c['b']     #进行调用
# #