create array


In [4]:
import numpy as np
import 

In [5]:
np.random.randn(10)

array([ 0.48692499,  0.17877253, -0.32353184,  0.78486116, -0.67842303,
       -0.34538756,  2.30375625,  0.96940662, -1.16190556, -0.43538753])

In [6]:
np.random.randint(10)

2

In [7]:
np.random.randint(10,size=(2,3))

array([[9, 5, 9],
       [8, 0, 3]])

In [8]:
np.random.randint(10,size=20).reshape(4,5)

array([[0, 1, 4, 3, 5],
       [9, 1, 3, 7, 0],
       [3, 8, 4, 8, 1],
       [4, 9, 3, 6, 7]])

In [9]:
a=np.random.randint(10,size=20).reshape(4,5)
b=np.random.randint(10,size=20).reshape(4,5)

In [10]:
a+b

array([[ 7,  6,  9,  5, 15],
       [ 1,  9,  4, 11,  6],
       [ 8, 11,  9, 13,  4],
       [ 4, 13,  9, 11,  7]])

In [11]:
a*b  #数组对应元素相乘，不是矩阵乘法

array([[10,  9, 14,  4, 56],
       [ 0, 14,  3, 30,  0],
       [ 0, 18,  8, 40,  4],
       [ 4, 42, 20, 30, 12]])

In [12]:
q=np.mat([[1,2,3],[4,5,6]])
p=np.mat([[1,2],[3,4],[5,6]])

In [13]:
np.mat(a)#矩阵与数组互换

matrix([[5, 3, 2, 4, 7],
        [1, 2, 1, 5, 0],
        [0, 2, 8, 8, 2],
        [2, 6, 4, 6, 3]])

In [14]:
a

array([[5, 3, 2, 4, 7],
       [1, 2, 1, 5, 0],
       [0, 2, 8, 8, 2],
       [2, 6, 4, 6, 3]])

In [15]:
q*p#矩阵乘法符合规则

matrix([[22, 28],
        [49, 64]])

Array function lib

In [16]:
a=np.random.randint(10,size=20).reshape(4,5)

In [17]:
a

array([[9, 5, 4, 5, 2],
       [9, 6, 8, 7, 8],
       [2, 7, 0, 6, 9],
       [6, 4, 2, 7, 5]])

In [18]:
sum(a)#列相加

array([26, 22, 14, 25, 24])

In [19]:
sum(a[0])#行相加

25

In [20]:
a[:,0:2]

array([[9, 5],
       [9, 6],
       [2, 7],
       [6, 4]])

In [21]:
sum(a[:,0:2])

array([26, 22])

In [22]:
a[:,0:1]#列返回

array([[9],
       [9],
       [2],
       [6]])

In [23]:
a[:,0]#以单数组返回

array([9, 9, 2, 6])

In [24]:
sum(a[:,0])

26

In [25]:
# arrayN维数组：
# list_2=[5,6,7,8]
# array_2=np.array([list_1,list_2])
# array_2.shape  （2，4）
# array_2.size
# array_2.dtype
# np.zeros(5) #全零
# np.eye(5) #单位矩阵
# a=np.arange(1,10)#创建一维数组用arange
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
# Input:
#  c[0:1,1:2]	# 第一个为行、二为列，记住从零开始、最后一个都不要，故相当于[0:0,1:1],0行的第一列
# Out[27]:
#          array([[2]])

# 正态分布随机数组：
# np.random.randn(10)
# np.random.randint(10,size=(2,3))
# np.random.randint(10,size=20).reshape(4,5)  #取10以内20个数，搞成45的数组


# 数组的函数：


# a[:,0:4]  #表示所有行，0到3列的元素

# a[:,0]  	#表示所有行，且是第一列，以数组返回
# array([1, 2, 4, 0])
# a[:,0:1]	#表示所有行，且是第一列，以列返回
# array([[1],
#        [2],
#        [4],
#        [0]])



# 创建矩阵：
# q=np.mat([[1,2,3],[4,5,6]])

# p=np.mat([[1,2],[3,4],[5,6]])
# np.mat(a)#矩阵与数组互换


In [26]:
x=np.arange(10)

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
score_list=np.random.randint(30,100,20)
score_list

array([81, 37, 91, 43, 65, 97, 93, 50, 31, 59, 40, 83, 35, 55, 46, 49, 55,
       74, 36, 33])

In [63]:
import pandas as pd
s2 = Series(np.random.rand(100),index=pd.date_range(start='20170101',periods=100))

In [64]:
t=pd.date_range(start='2017-01-01',end='2017-02-01',freq='w')

In [65]:
s2

2017-01-01    0.140938
2017-01-02    0.429244
2017-01-03    0.589315
2017-01-04    0.020201
2017-01-05    0.440960
2017-01-06    0.792690
2017-01-07    0.472845
2017-01-08    0.421831
2017-01-09    0.244639
2017-01-10    0.612651
2017-01-11    0.135461
2017-01-12    0.002564
2017-01-13    0.749217
2017-01-14    0.230242
2017-01-15    0.908710
2017-01-16    0.270517
2017-01-17    0.201417
2017-01-18    0.247055
2017-01-19    0.221822
2017-01-20    0.939826
2017-01-21    0.063380
2017-01-22    0.268782
2017-01-23    0.584288
2017-01-24    0.707229
2017-01-25    0.293856
2017-01-26    0.405720
2017-01-27    0.053494
2017-01-28    0.041184
2017-01-29    0.081220
2017-01-30    0.442935
                ...   
2017-03-12    0.040664
2017-03-13    0.539132
2017-03-14    0.844086
2017-03-15    0.715450
2017-03-16    0.772850
2017-03-17    0.064573
2017-03-18    0.328584
2017-03-19    0.717127
2017-03-20    0.498239
2017-03-21    0.641492
2017-03-22    0.886316
2017-03-23    0.498313
2017-03-24 